# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

theme: jekyll-theme-midnight
title: David Evangelista
email: victor.escorcia@kaust.edu.sa


description: > # this means to ignore newlines until "baseurl:"
  Mathematician
baseurl: "" # the subpath of your site, e.g. /blog
url: "davidsevangelista.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_username:  davidsevangelista
facebook_username: davidsevangelista
#google_plus_username: 114176447295025597712
#twitter_username: 3scorciav

# Address information
address_street: 4700 KAUST
address_city: Thuwal
address_state: KSA
address_zip: 23955-6900

# Build settings
#markdown: kramdown

# My variables
#cv_url: https://drive.google.com/open?id=0B0ZXjo_p8lHBbVkzLXk5UWplUkU
#Contact GitHub API Training Shop Blog About
